---
apiVersion: cluster.x-k8s.io/v1alpha4
kind: Cluster
metadata:
  name: "test"
spec:
  clusterNetwork:
    pods:
      cidrBlocks: ["192.168.0.0/16"]
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
    kind: KINDCluster
    name: "test"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
kind: KINDCluster
metadata:
  name: "test"
spec:
  name: "Testing attention please"